// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVoV5FaZS42GJxdxh8Dbb3azaZFOMzUB8',
    appId: '1:832212547837:web:cdba1676318ef7de88e694',
    messagingSenderId: '832212547837',
    projectId: 'second-web-evolui-54432',
    authDomain: 'second-web-evolui-54432.firebaseapp.com',
    storageBucket: 'second-web-evolui-54432.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYq9WZVxhlRyEtdcHQ_0yUPHtZ6TzfrWk',
    appId: '1:832212547837:android:2c92686ff7c3dc4288e694',
    messagingSenderId: '832212547837',
    projectId: 'second-web-evolui-54432',
    storageBucket: 'second-web-evolui-54432.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8b_T4RQ57NT1byHyb7VmZpS3VAWGvSsM',
    appId: '1:832212547837:ios:747b7e8f2cfecad688e694',
    messagingSenderId: '832212547837',
    projectId: 'second-web-evolui-54432',
    storageBucket: 'second-web-evolui-54432.appspot.com',
    iosBundleId: 'br.com.webevolui.second.webevoluiSecond',
  );
}
